version: 0.2

env:
  secrets-manager:
    LOGIN: local/sonar:sonartoken
    HOST: local/sonar:HOST
    Organization: local/sonar:Organization
    Project: local/sonar:Project

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - npm install -g npm@latest
      - npm install
  build:
    commands:
      - npm run build
      - npm test
      - npm run sonar
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$(aws secretsmanager get-secret-value --secret-id local/sonar:Project --query SecretString --output text) >result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi


